### ISSUE TITLE
신고하기 기능 추가

### ISSUE THREAD

**Issue by kihwankim** [YAPP-19th/Android-Team-2-Backend#75]
### 신고 시나리오
- 일반적인 사유로 Food가 3번 신고당한 경우 Food 비공개 처리
- 일반적인 사유로 3번 신고당한 Food가 5개가 된 경우 모든 Food 비공개 및 User 정지
- 일반적인 사유로 User가 5번 신고를 당하면 User 정지
- 특수한 사유(가학적, 유해한, 음란물)로 Food가 신고당한 경우 Food 비공개 및 User 정지
- 특수한 사유(가학적, 유해한, 음란물)로 User가 신고당한 경우 Food 비공개 및 User 정지

---

###  도메인 도출

- User의 NORMAL, BANNED Status 필요
- User에서 이 계정에 신고당한 Food의 수 파악이 필요
- User에서 이 계정이 신고당하여 감점당한 Count 파악이 필요
- Food의 Status에 BANNED 상태 추가 필요
- Food에서 이 Food의 신고 점수 파악 필요

---

### issue

1. 만약 잘못된 신고에 대해 복구를해야하는 경우
- Food는 Status를 추가하는 경우 vs 점수로 sort시 조건을 추가하는 경우
- 신고 사유에 대한 history를 남기려면 점수 방식은 별로라고 생각

2. Food에 신고가 쌓여 User가 정지되는 경우
- 정확한 History 추척을 어떤 방식으로 해야하는지

3. 연관관계
- Food Report와 User의 연관 관계가 떠오르지 않음

**Comment by dev-donghwan** [comment]
@kihwankim 
issue 부분 생각 한번 말씀해주실 수 있나요!?

**Comment by kihwankim** [comment]
솔직히말 씀드리면 스코어로하고 banned normal advanced_bannded로 3개로 나눠서 처음 잠금 된 경우는 banned로 그리고 풀리고나서 다시 banned가되면 real bannded로 설정하고 history에 emun status 를 남기면  좋을듯 힙니다.
왜냐면 몇번 락길리고 풀렸는지 확인 가능 + 상습적 잠금 유무 판단도 좋은 구조라고 생각합니다.

이렇게하면 score변수를 써도 락 기록도 같이 볼 수 있을거 같습니다
